### ISSUE TITLE
Chrome Plugin

### ISSUE THREAD

**Issue by edgrosvenor** [EXACTsports/directory-assistance#1]
A single button in the browser that, when clicked, does the following:

Load this script and cause it to run: //exactsports.github.io/directory-assistance/js/assist.js

If you need to wrap the javascript into a function, load the script, and then call the function in order to make it work, that's fine. It would be ideal if this could be managed without a page reload, but I can live with it if you have to reload the page.

The desired result:

http://www.depaulbluedemons.com/staffdir/depa-staffdir.html

As you can see, there are envelopes in the right column that represent the email addresses of the coach. This script simply replaces those envelopes with the actual email address. That lets us simply do a copy / paste operation to import the data from the directory.

**Comment by shoover56** [comment]
Welp it's there. PrepHero logo, click it, boom, that.

**Comment by edgrosvenor** [comment]
This is a thing of beauty. I'm sure I'll find all sorts of other extremely useful things to do with it. Thank you!
